    name: Run Ansible Playbook

    on: [push]

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Run Ansible Playbook
            uses: dawidd6/action-ansible-playbook@v2
            with:
              playbook: deploy.yml
              directory: ./ansible
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              inventory: |
                [all]
                your_server_ip
